<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>claudiosoft</groupId>
    <artifactId>CTUtils</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <scm>
        <connection>scm:git:git@https://github.com/claudio-tortorelli/CTUtils.git</connection>
        <tag>HEAD</tag>
    </scm>
    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <exec.mainClass>claudiosoft.utils.Utils</exec.mainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.ini4j</groupId>
            <artifactId>ini4j</artifactId>
            <version>0.5.4</version>        
        </dependency>             
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>         
    </dependencies>    
</project>